# Generated by Django 5.0 on 2025-11-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_no'), ('section', 'roll_number')},
        ),
    ]
